<template>
<div>
  <p>The following document outlines the terms of use of memecreator.io. Before using any of the services, you are required to read, understand and agree to these terms. You may only create an account after reading and accepting these terms.</p>
  <h2 class="Regular 16sp">About memecreator.io</h2>
  <p>
    memecreator.io («the Service») is published by memecreator. By using the Service, you agree to be bound by the following terms and conditions («Terms of Service»). Any new features or tools added to the Service shall also be subject to the Terms of Service. “Users” may have personal user accounts. There are also accounts with administrative permissions which can log in to the Service administration panel. Any party accessing the site without a user account is termed a «Viewer». «Content» includes, but is not limited to, data, text, information, screen names, graphics, photos, profiles, audio, video, links, photos, comments and customizations, posted by memecreator and users.
    -
  </p>
  <h2 class="Regular 16sp">Using memecreator.io</h2>
  <p>In order to use the Service, you must create a user account. User profiles are unique and consist of at least a e-mail address, name and an encrypted password. You are also solely responsible for the content posted by you, and memecreator disclaims any liability resulting from the Content posted on and activity occurring on your site and under your account.</p>
  <h2 class="Regular 16sp">Plans</h2>
  <p>memecreator provides the following plans: (Fill in) The plans include unlimited storage, full product capabilities and upgrades, but this may change in the future. If there are changes made, the Client will be given notice. If we see that the content attracts a high amount of traffic, there is a possibility that memecreator will hide the video from public view. The client will be given notice if this occurs. memecreator reserves the right to terminate the Service at any time.</p>
  <h2 class="Regular 16sp">Sharing content provisions and liabilities</h2>
  <p>If you have an account with administrative permissions, you may upload your own material to memecreator. You can give other users access to view and to work with such Content. memecreator claims intellectual property rights over the Content. You must ensure that the Content’s authors consent to making the material accessible for viewing through your site. People present in the Content must consent to making the material accessible for viewing through your site. This applies to all Content.</p>
  <h2 class="Regular 16sp">Code of conduct</h2>
  <p>You may not use the Service for illegal purposes. You must not, in the use of the Service, violate any copyrights or trademark laws, laws in your jurisdiction and the laws of Norway (including, but not limited to the Norwegian Act on Processing of Personal Data, the Marketing Act or the penal code). memecreator reserves the right to take necessary action to comply with the law and with judicial rulings, including, but not limited to, removing your Content from the Service without notice. You agree not to use the Services to upload, post, e-mail, transmit or otherwise make available any Content that is unlawful, harmful, threatening, pornographic, violent, abusive, harassing, tortious, defamatory, vulgar, obscene, libelous, invasive of another’s privacy, hateful, or racially, ethnically or otherwise objectionable. memecreator reserves the right to remove any site hosting such content from the Service without notice. You shall observe common «etiquette» in presentation of the content and is liable for any Content in violation of these terms. If memecreator receives a claim from the third party on account of violation of these Terms of Service, which result from your material breach, memecreator will forward the claim to you. memecreator reserves the right to take any action to protect its network and computing resources against harmful activity stemming from the users actions. If such activity interferes with the operation of the Service, actions include, but are not limited to, temporarily suspending, degrading or terminating access to the Service for some or all users.</p>
  <h2 class="Regular 16sp">Separation of ownership</h2>
  <p>You agree not to reproduce, duplicate, copy, sell, resell or exploit any portion of the Service, use of the Service, or access to the Service without the expressed written permission by memecreator. You understand that by uploading material, you accept that memecreator and others, whom you give access to the material, obtain a right to use this material as stated in the Terms of Service.</p>
  <h2 class="Regular 16sp">Limitation of liability</h2>
  <p>memecreator does not guarantee that the service is available at all times. The service is offered «as is» and «as available» and delivered on a best effort basis. memecreator disclaims any liability for any loss – direct as well as indirect, incidental, special, consequential or exemplary – which may be inflicted on you and includes damages for loss of profits, goodwill, use, data or other intangible losses resulting from: (i) using the Service; (ii) inability to use the Service; (iii) defects in the Service; (iv) the discontinuation of the Service; (v) the cost of procurement of substitute goods and services resulting from any goods, data, information or services purchased or obtained or messages received or transactions entered into through or from Service; (vi) unauthorized access to or alteration of your transmission or data; (vii) statements or conduct of any third party on the Service; (viii) or any other matter relating to the Service. memecreator is not liable for any loss resulting from damages inflicted by others including, but not limited to Users and Visitors. You understand that the technical processing and transmission of the Service, including your Content, may be transferred unencrypted and involve (i) transmissions over various networks, and (ii) changes to conform and adapt to technical requirements of connecting networks or devices.
  </p><h2 class="Regular 16sp">Other</h2>
  <p>memecreator shall be entitled to terminate the agreement without notice, in whole or in part, in case of your material breach, which is any neglecting of the obligations assigned to you in accordance with these terms. memecreator reserves the right to change these Terms of Service at any time. The Client consents to the fact that the Terms of Service are governed by the laws of Norway. The Client agrees to the exclusive jurisdiction of the courts in Oslo, Norway, over any legal action or proceeding arising from these Terms of Service of its use of the Service. The Client agrees that memecreator may selectively enforce the rights and provisions of the Terms of Service. The Client also agrees that if any provisions of the Terms of Service are found to be invalid or unenforceable, the Client nevertheless agrees to give effect to the intentions reflected in the provision, and all other provisions remain in effect. These Terms of Service constitute the entire agreement between you and memecreator regarding the use of the Service, unless otherwise specified in writing. No modification to these Terms of Service shall be valid unless executed in writing. memecreator disclaims any liability for loss or damage of the Client’s data, including uploaded material. The Client is solely responsible for backing up of data and solely responsible for protection of backup copies.</p>
</div>
</template>

<script>
export default {};
</script>
